version: '3.9'

networks:
  cfp:
    driver: bridge

services:
  cfp-service:
    container_name: cfp-service
    image: cfp-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_HTTP_PORTS=8080
    networks:
      - cfp
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: postgres
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cfp
    ports:
      - "5432:5432"
    networks:
      - cfp
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 3